spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/healthapp_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: false
