apiVersion: v1
kind: Secret
metadata:
  name: healthapp-secrets
  namespace: healthapp
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql.healthapp.svc.cluster.local:5432/healthapp_db
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: change-me

  EVENTS_DB_URL: jdbc:postgresql://postgresql-events.healthapp.svc.cluster.local:5432/healthapp_events_db
  EVENTS_DB_USERNAME: postgres
  EVENTS_DB_PASSWORD: change-me

  KAFKA_BOOTSTRAP_SERVERS: kafka.healthapp.svc.cluster.local:9092

  FHIR_BASE_URL: http://fhir-api.healthapp.svc.cluster.local:8081/fhir
  OLLAMA_BASE_URL: http://ollama.healthapp.svc.cluster.local:11434
